name: Weekly Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 UTC every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.0

      - name: Update dependencies
        run: pnpm update --latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates the project dependencies to their latest versions.
            Please review the changes and merge if everything looks good.
          branch: dependency-updates
          delete-branch: true
          labels: dependencies
